import type { Recipe, Resource, ResourceType } from "../types/game";

export const RESOURCES: Record<ResourceType, Resource> = {
  iron: {
    type: "iron",
    name: "Iron",
    rarity: "common",
    weight: 5,
    color: "#8B7355",
    icon: "⬡",
  },
  silicon: {
    type: "silicon",
    name: "Silicon",
    rarity: "common",
    weight: 3,
    color: "#C8C8B4",
    icon: "◈",
  },
  carbon: {
    type: "carbon",
    name: "Carbon",
    rarity: "common",
    weight: 2,
    color: "#3D3D3D",
    icon: "◆",
  },
  titanium: {
    type: "titanium",
    name: "Titanium",
    rarity: "uncommon",
    weight: 8,
    color: "#7EB8C9",
    icon: "⬢",
  },
  platinum: {
    type: "platinum",
    name: "Platinum",
    rarity: "uncommon",
    weight: 15,
    color: "#E5E4E2",
    icon: "◉",
  },
  rareEarth: {
    type: "rareEarth",
    name: "Rare Earth",
    rarity: "uncommon",
    weight: 6,
    color: "#9B59B6",
    icon: "✦",
  },
  exoticMatter: {
    type: "exoticMatter",
    name: "Exotic Matter",
    rarity: "rare",
    weight: 1,
    color: "#FF6B35",
    icon: "⚡",
  },
  darkMatter: {
    type: "darkMatter",
    name: "Dark Matter",
    rarity: "rare",
    weight: 0.5,
    color: "#8844CC",
    icon: "◑",
  },
  quantumCrystals: {
    type: "quantumCrystals",
    name: "Quantum Crystals",
    rarity: "rare",
    weight: 2,
    color: "#00FFFF",
    icon: "💎",
  },
};

export const RECIPES: Recipe[] = [
  {
    id: "hull-plating",
    name: "Reinforced Hull Plating",
    category: "hull",
    componentType: "hullUpgrade",
    ingredients: { iron: 20, carbon: 10 },
    result: {
      type: "hullUpgrade",
      name: "Reinforced Hull Plating",
      description: "Increases max hull integrity by 25",
      stats: { maxHull: 25 },
    },
  },
  {
    id: "titanium-hull",
    name: "Titanium Hull Upgrade",
    category: "hull",
    componentType: "hullUpgrade",
    ingredients: { titanium: 15, silicon: 10, iron: 5 },
    result: {
      type: "hullUpgrade",
      name: "Titanium Hull Upgrade",
      description: "Increases max hull integrity by 50",
      stats: { maxHull: 50 },
    },
  },
  {
    id: "engine-boost",
    name: "Plasma Engine Boost",
    category: "engine",
    componentType: "engineUpgrade",
    ingredients: { silicon: 15, iron: 10, carbon: 5 },
    result: {
      type: "engineUpgrade",
      name: "Plasma Engine Boost",
      description: "Increases max speed by 20%",
      stats: { speed: 10, maxFuel: 20 },
    },
  },
  {
    id: "ion-engine",
    name: "Ion Drive Engine",
    category: "engine",
    componentType: "engineUpgrade",
    ingredients: { titanium: 20, rareEarth: 5, silicon: 10 },
    result: {
      type: "engineUpgrade",
      name: "Ion Drive Engine",
      description: "High efficiency ion propulsion",
      stats: { speed: 20, maxFuel: 50 },
    },
  },
  {
    id: "mining-laser-mk2",
    name: "Mining Laser Mk.II",
    category: "weapons",
    componentType: "miningLaser",
    ingredients: { iron: 15, silicon: 20, carbon: 8 },
    result: {
      type: "miningLaser",
      name: "Mining Laser Mk.II",
      description: "Faster extraction rate",
      stats: { miningPower: 15 },
    },
  },
  {
    id: "quantum-drill",
    name: "Quantum Drill",
    category: "weapons",
    componentType: "miningLaser",
    ingredients: { quantumCrystals: 2, titanium: 10, platinum: 5 },
    result: {
      type: "miningLaser",
      name: "Quantum Drill",
      description: "Extracts rare resources more efficiently",
      stats: { miningPower: 40 },
    },
  },
  {
    id: "energy-shield",
    name: "Energy Shield",
    category: "utilities",
    componentType: "shield",
    ingredients: { silicon: 20, rareEarth: 8, iron: 10 },
    result: {
      type: "shield",
      name: "Energy Shield",
      description: "Absorbs 25 damage before hull",
      stats: { shieldStrength: 25 },
    },
  },
  {
    id: "deep-scanner",
    name: "Deep Space Scanner",
    category: "utilities",
    componentType: "scanner",
    ingredients: { silicon: 15, platinum: 3, carbon: 10 },
    result: {
      type: "scanner",
      name: "Deep Space Scanner",
      description: "Reveals resource composition of asteroids",
      stats: {},
    },
  },
  {
    id: "cargo-expander",
    name: "Cargo Bay Expander",
    category: "hull",
    componentType: "hullUpgrade",
    ingredients: { iron: 25, carbon: 15 },
    result: {
      type: "hullUpgrade",
      name: "Cargo Bay Expander",
      description: "Increases cargo capacity by 250kg",
      stats: { maxCargo: 250 },
    },
  },
  {
    id: "exotic-refinery",
    name: "Exotic Matter Refinery",
    category: "utilities",
    componentType: "refinery",
    ingredients: { exoticMatter: 3, darkMatter: 2, platinum: 8 },
    result: {
      type: "refinery",
      name: "Exotic Matter Refinery",
      description: "Processes exotic resources for maximum yield",
      stats: { miningPower: 25 },
    },
  },
];

export const PHYSICS = {
  MAX_SPEED: 50,
  BOOST_MULTIPLIER: 2.5,
  ACCELERATION: 15,
  DRAG: 0.97,
  BRAKE_FORCE: 0.85,
  ROTATION_SPEED: 1.5,
  FUEL_CONSUMPTION_RATE: 0.03,
  BOOST_FUEL_RATE: 0.12,
  MINING_DURATION: 3000,
  MINING_RANGE: 25,
  COLLISION_DAMAGE: 8,
  COLLISION_DISTANCE: 3,
};

export const STATION_POSITIONS: [number, number, number][] = [
  [150, 20, 80],
  [-250, -30, -180],
  [50, -80, 220],
];

export const SAVE_KEY = "frontier-save-v1";
