/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameSave = IDL.Record({
  'credits' : IDL.Nat,
  'fuel' : IDL.Nat,
  'hull' : IDL.Nat,
  'inventory' : IDL.Text,
  'components' : IDL.Text,
  'position' : IDL.Text,
});
export const PlayerProfile = IDL.Record({
  'username' : IDL.Text,
  'totalPlayTime' : IDL.Nat,
  'achievements' : IDL.Vec(IDL.Text),
});
export const ScoreEntry = IDL.Record({
  'playerId' : IDL.Principal,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getGameState' : IDL.Func([IDL.Principal], [GameSave], ['query']),
  'getPlayerProfile' : IDL.Func([IDL.Principal], [PlayerProfile], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'registerPlayer' : IDL.Func([IDL.Text], [], []),
  'saveGameState' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateHighScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameSave = IDL.Record({
    'credits' : IDL.Nat,
    'fuel' : IDL.Nat,
    'hull' : IDL.Nat,
    'inventory' : IDL.Text,
    'components' : IDL.Text,
    'position' : IDL.Text,
  });
  const PlayerProfile = IDL.Record({
    'username' : IDL.Text,
    'totalPlayTime' : IDL.Nat,
    'achievements' : IDL.Vec(IDL.Text),
  });
  const ScoreEntry = IDL.Record({
    'playerId' : IDL.Principal,
    'score' : IDL.Nat,
  });
  
  return IDL.Service({
    'getGameState' : IDL.Func([IDL.Principal], [GameSave], ['query']),
    'getPlayerProfile' : IDL.Func([IDL.Principal], [PlayerProfile], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'registerPlayer' : IDL.Func([IDL.Text], [], []),
    'saveGameState' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHighScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };